---
name: Sentry error
about: Used for tracking Sentry errors
title: 'MODULE: Neuer Sentry-Error'
labels: error
assignees: ''

---

Sentry: <!-- Link zum Sentry Issue -->
Exception: <!-- Name der Exception -->
Action: <!-- Name von betroffenem Controller und Action -->
Further context:
<!-- ACHTUNG: Bitte sensible Kundendaten hier anonymisieren! -->
